package main

import (
	"cmp"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/goccy/go-yaml"
)

const (
	outputFile     = ".goreleaser.yaml"
	dockerfileGlob = "images/*/Dockerfile"
	registryURL    = "ghcr.io/benfiola"
)

type ImageConfig struct {
	Platforms []string `json:"platforms,omitempty"`
}

type GoreleaserTarget struct {
	Dockerfile     string
	Binary         string
	Name           string
	ImagePlatforms []string
}

func (gt GoreleaserTarget) GetBinaryArchs() []string {
	archMap := map[string]bool{}
	for _, platform := range gt.ImagePlatforms {
		parts := strings.Split(platform, "/")
		arch := parts[len(parts)-1]
		archMap[arch] = true
	}
	archs := []string{}
	for arch := range archMap {
		archs = append(archs, arch)
	}
	return archs
}

func (gt GoreleaserTarget) GetImageUrl() string {
	return fmt.Sprintf("%s/{{ .ProjectName }}/%s", registryURL, gt.Name)
}

func findTargets() ([]GoreleaserTarget, error) {
	dockerfiles, err := filepath.Glob(dockerfileGlob)
	if err != nil {
		return nil, fmt.Errorf("glob %q: %w", dockerfileGlob, err)
	}

	targets := make([]GoreleaserTarget, len(dockerfiles))
	for i, dockerfile := range dockerfiles {
		parent := filepath.Dir(dockerfile)

		path := filepath.Join(parent, "main.go")
		binary := ""
		if _, err := os.Stat(path); err == nil {
			binary = path
		} else if !os.IsNotExist(err) {
			return nil, err
		}

		path = filepath.Join(parent, "image.yaml")
		imagePlatforms := []string{"linux/amd64", "linux/arm64"}
		if _, err := os.Stat(path); err == nil {
			configBytes, err := os.ReadFile(path)
			if err != nil {
				return nil, err
			}

			config := ImageConfig{}
			if err := yaml.Unmarshal(configBytes, &config); err != nil {
				return nil, err
			}

			if len(config.Platforms) != 0 {
				imagePlatforms = config.Platforms
			}
		} else if !os.IsNotExist(err) {
			return nil, err
		}

		name := filepath.Base(filepath.Dir(dockerfile))
		targets[i] = GoreleaserTarget{Dockerfile: dockerfile, Binary: binary, Name: name, ImagePlatforms: imagePlatforms}
	}
	return targets, nil
}

func buildReleaseFooter(targets []GoreleaserTarget) string {
	if len(targets) == 0 {
		return ""
	}

	footer := "**Docker Images:**\n"
	for _, target := range targets {
		footer += fmt.Sprintf("- `%s:{{ .Version }}`\n", target.GetImageUrl())
	}
	return footer
}

func buildConfig(targets []GoreleaserTarget) map[string]any {
	builds := []map[string]any{}
	for _, target := range targets {
		if target.Binary == "" {
			continue
		}
		build := map[string]any{
			"binary":  target.Name,
			"id":      target.Name,
			"goos":    []string{"linux"},
			"goarch":  target.GetBinaryArchs(),
			"ldflags": []string{"-X {{ .ModulePath }}/internal/info.Version={{ .Version }}"},
			"main":    target.Binary,
		}
		builds = append(builds, build)
	}

	dockers := make([]map[string]any, len(targets))
	for i, target := range targets {
		dockers[i] = map[string]any{
			"dockerfile": target.Dockerfile,
			"id":         target.Name,
			"images":     []string{target.GetImageUrl()},
			"platforms":  target.ImagePlatforms,
			"tags":       []string{"{{ .Version }}"},
		}
	}

	return map[string]any{
		"version":      2,
		"project_name": "game-server-images",
		"archives": []map[string]any{{
			"allow_different_binary_count": true,
		}},
		"builds": builds,
		"release": map[string]any{
			"footer": buildReleaseFooter(targets),
		},
		"changelog": map[string]any{
			"use": "github-native",
		},
		"dockers_v2": dockers,
	}
}

func main() {
	targets, err := findTargets()
	if err != nil {
		log.Fatalf("find targets: %v", err)
	}
	slices.SortFunc(targets, func(a, b GoreleaserTarget) int { return cmp.Compare(a.Dockerfile, b.Dockerfile) })

	config := buildConfig(targets)

	header := []byte("# this was auto-generated by ./hack/generate-goreleaser - do not edit\n")
	configBytes, err := yaml.Marshal(&config)
	if err != nil {
		log.Fatalf("marshal config: %v", err)
	}

	output := append(header, configBytes...)
	if err := os.WriteFile(outputFile, output, 0644); err != nil {
		log.Fatalf("write output: %v", err)
	}
}
