package main

import (
	"cmp"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"slices"

	"github.com/goccy/go-yaml"
)

const (
	outputFile     = ".goreleaser.yaml"
	cmdGlob        = "cmd/*/main.go"
	dockerfileGlob = "images/*/.goreleaser.Dockerfile"
	registryURL    = "ghcr.io/benfiola/"
)

type Command struct {
	ID   string
	Path string
}

type Image struct {
	Name string
	Path string
}

func findCommands() ([]Command, error) {
	mainFiles, err := filepath.Glob(cmdGlob)
	if err != nil {
		return nil, fmt.Errorf("glob %q: %w", cmdGlob, err)
	}

	commands := make([]Command, len(mainFiles))
	for i, mainFile := range mainFiles {
		id := filepath.Base(filepath.Dir(mainFile))
		commands[i] = Command{ID: id, Path: mainFile}
	}
	return commands, nil
}

func findImages() ([]Image, error) {
	dockerfiles, err := filepath.Glob(dockerfileGlob)
	if err != nil {
		return nil, fmt.Errorf("glob %q: %w", dockerfileGlob, err)
	}

	images := make([]Image, len(dockerfiles))
	for i, dockerfile := range dockerfiles {
		name := filepath.Base(filepath.Dir(dockerfile))
		images[i] = Image{Name: name, Path: dockerfile}
	}
	return images, nil
}

func buildReleaseFooter(images []Image) string {
	if len(images) == 0 {
		return ""
	}

	footer := "**Docker Images:**\n"
	for _, img := range images {
		imageURL := fmt.Sprintf("%s{{ .ProjectName }}/%s", registryURL, img.Name)
		footer += fmt.Sprintf("- `%s:{{ .Version }}`\n", imageURL)
	}
	return footer
}

func buildConfig(commands []Command, images []Image) map[string]any {
	builds := make([]map[string]any, len(commands))
	for i, cmd := range commands {
		builds[i] = map[string]any{
			"id":      cmd.ID,
			"goos":    []string{"linux"},
			"goarch":  []string{"arm64", "amd64"},
			"ldflags": []string{"-X {{ .ModulePath }}/internal/info.Version={{ .Version }}"},
			"main":    cmd.Path,
		}
	}

	dockers := make([]map[string]any, len(images))
	for i, img := range images {
		dockers[i] = map[string]any{
			"dockerfile": img.Path,
			"images": []string{
				fmt.Sprintf("%s{{ .ProjectName }}/%s", registryURL, img.Name),
			},
			"platforms": []string{"linux/arm64", "linux/amd64"},
			"tags": []string{
				"{{ .Version }}",
			},
		}
	}

	return map[string]any{
		"version":      2,
		"project_name": "game-server-images",
		"builds":       builds,
		"release": map[string]any{
			"footer": buildReleaseFooter(images),
		},
		"changelog": map[string]any{
			"use": "github-native",
		},
		"dockers_v2": dockers,
	}
}

func main() {
	commands, err := findCommands()
	if err != nil {
		log.Fatalf("find commands: %v", err)
	}
	slices.SortFunc(commands, func(a, b Command) int { return cmp.Compare(a.Path, b.Path) })

	images, err := findImages()
	if err != nil {
		log.Fatalf("find images: %v", err)
	}
	slices.SortFunc(images, func(a, b Image) int { return cmp.Compare(a.Path, b.Path) })

	config := buildConfig(commands, images)

	header := []byte("# this was auto-generated by ./hack/generate-goreleaser - do not edit\n")
	configBytes, err := yaml.Marshal(&config)
	if err != nil {
		log.Fatalf("marshal config: %w", err)
	}

	output := append(header, configBytes...)
	if err := os.WriteFile(outputFile, output, 0644); err != nil {
		log.Fatalf("write output: %v", err)
	}
}
