package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"slices"

	"github.com/goccy/go-yaml"
)

const (
	templateFile   = ".goreleaser.template.yaml"
	outputFile     = ".goreleaser.yaml"
	dockerfileGlob = "images/*/.goreleaser.Dockerfile"
	registryURL    = "ghcr.io/benfiola/"
)

var platforms = []string{"linux/arm64", "linux/amd64"}

type Image string

func (i Image) GetName() string {
	return filepath.Base(filepath.Dir(string(i)))
}

func findImages() ([]Image, error) {
	dockerfiles, err := filepath.Glob(dockerfileGlob)
	if err != nil {
		return nil, fmt.Errorf("glob %q: %w", dockerfileGlob, err)
	}

	images := make([]Image, len(dockerfiles))
	for i, dockerfile := range dockerfiles {
		images[i] = Image(dockerfile)
	}
	return images, nil
}

type Template map[string]any

func readTemplate(file string) (Template, error) {
	templateBytes, err := os.ReadFile(file)
	if err != nil {
		return nil, fmt.Errorf("read %q: %w", file, err)
	}

	data := map[string]any{}
	if err := yaml.Unmarshal(templateBytes, &data); err != nil {
		return nil, fmt.Errorf("unmarshal %q: %w", file, err)
	}

	return Template(data), nil
}

func (t Template) AddImage(image Image) {
	entry := map[string]any{
		"dockerfile": image,
		"images": []string{
			fmt.Sprintf("%s/{{ .ProjectName }}/%s", registryURL, image.GetName()),
		},
		"platforms": platforms,
		"tags": []string{
			"{{ .Version }}",
		},
	}

	dockerKey := "dockers_v2"
	dockers, ok := t[dockerKey].([]map[string]any)
	if !ok {
		dockers = []map[string]any{}
	}
	t[dockerKey] = append(dockers, entry)
}

func (t Template) Marshal() ([]byte, error) {
	header := []byte("# this was auto-generated by ./hack/generate-goreleaser - do not edit\n")
	templateBytes, err := yaml.Marshal(&t)
	if err != nil {
		return nil, fmt.Errorf("marshal yaml: %w", err)
	}
	return append(header, templateBytes...), nil
}

func main() {
	template, err := readTemplate(templateFile)
	if err != nil {
		log.Fatalf("read template: %v", err)
	}

	images, err := findImages()
	if err != nil {
		log.Fatalf("find images: %v", err)
	}
	slices.Sort(images)

	for _, image := range images {
		template.AddImage(image)
	}

	templateBytes, err := template.Marshal()
	if err != nil {
		log.Fatalf("marshal template: %v", err)
	}

	if err := os.WriteFile(outputFile, templateBytes, 0644); err != nil {
		log.Fatalf("write output: %v", err)
	}
}
